export const API_ERRORS = {
  REQUIRED_FIELDS: 'REQUIRED_FIELDS',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  STOCK_UNAVAILABLE: 'STOCK_UNAVAILABLE',
  INVALID_REQUEST: 'INVALID_REQUEST',
  SERVER_ERROR: 'SERVER_ERROR',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export type ApiErrorCode = typeof API_ERRORS[keyof typeof API_ERRORS];
