console.log('PayU Configuration Check:');
console.log('========================');
console.log('PAYU_MERCHANT_ID:', process.env.PAYU_MERCHANT_ID ? '✓ Set' : '✗ Missing');
console.log('PAYU_API_KEY:', process.env.PAYU_API_KEY ? '✓ Set' : '✗ Missing');
console.log('PAYU_API_LOGIN:', process.env.PAYU_API_LOGIN ? '✓ Set' : '✗ Missing');
console.log('PAYU_ACCOUNT_ID:', process.env.PAYU_ACCOUNT_ID ? '✓ Set' : '✗ Missing');
console.log('PAYU_TEST_MODE:', process.env.PAYU_TEST_MODE);
console.log('');
console.log('Values (first 4 chars):');
console.log('MERCHANT_ID:', process.env.PAYU_MERCHANT_ID?.substring(0, 4) + '...');
console.log('ACCOUNT_ID:', process.env.PAYU_ACCOUNT_ID?.substring(0, 4) + '...');
